# This file has been generated by node2nix 1.9.0. Do not edit!

{ nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? [ ] }:

let
  sources = {
    "@actions/core-1.2.6" = {
      name = "_at_actions_slash_core";
      packageName = "@actions/core";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/core/-/core-1.2.6.tgz";
        sha512 = "ZQYitnqiyBc3D+k7LsgSBmMDVkOVidaagDG7j3fOym77jNunWRuYx7VSHa9GNfFZh+zh61xsCjRj4JxMZlDqTA==";
      };
    };
    "@actions/exec-1.0.4" = {
      name = "_at_actions_slash_exec";
      packageName = "@actions/exec";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/exec/-/exec-1.0.4.tgz";
        sha512 = "4DPChWow9yc9W3WqEbUj8Nr86xkpyE29ZzWjXucHItclLbEW6jr80Zx4nqv18QL6KK65+cifiQZXvnqgTV6oHw==";
      };
    };
    "@actions/github-4.0.0" = {
      name = "_at_actions_slash_github";
      packageName = "@actions/github";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/github/-/github-4.0.0.tgz";
        sha512 = "Ej/Y2E+VV6sR9X7pWL5F3VgEWrABaT292DRqRU6R4hnQjPtC/zD3nagxVdXWiRQvYDh8kHXo7IDmG42eJ/dOMA==";
      };
    };
    "@actions/http-client-1.0.11" = {
      name = "_at_actions_slash_http-client";
      packageName = "@actions/http-client";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/http-client/-/http-client-1.0.11.tgz";
        sha512 = "VRYHGQV1rqnROJqdMvGUbY/Kn8vriQe/F9HR2AlYHzmKuM/p3kjNuXhmdBfcVgsvRWTz5C5XW5xvndZrVBuAYg==";
      };
    };
    "@actions/io-1.1.0" = {
      name = "_at_actions_slash_io";
      packageName = "@actions/io";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/io/-/io-1.1.0.tgz";
        sha512 = "PspSX7Z9zh2Fyyuf3F6BsYeXcYHfc/VJ1vwy2vouas95efHVd42M6UfBFRs+jY0uiMDXhAoUtATn9g2r1MaWBQ==";
      };
    };
    "@octokit/auth-token-2.4.5" = {
      name = "_at_octokit_slash_auth-token";
      packageName = "@octokit/auth-token";
      version = "2.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-token/-/auth-token-2.4.5.tgz";
        sha512 = "BpGYsPgJt05M7/L/5FoE1PiAbdxXFZkX/3kDYcsvd1v6UhlnE5e96dTDr0ezX/EFwciQxf3cNV0loipsURU+WA==";
      };
    };
    "@octokit/core-3.4.0" = {
      name = "_at_octokit_slash_core";
      packageName = "@octokit/core";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/core/-/core-3.4.0.tgz";
        sha512 = "6/vlKPP8NF17cgYXqucdshWqmMZGXkuvtcrWCgU5NOI0Pl2GjlmZyWgBMrU8zJ3v2MJlM6++CiB45VKYmhiWWg==";
      };
    };
    "@octokit/endpoint-6.0.11" = {
      name = "_at_octokit_slash_endpoint";
      packageName = "@octokit/endpoint";
      version = "6.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/endpoint/-/endpoint-6.0.11.tgz";
        sha512 = "fUIPpx+pZyoLW4GCs3yMnlj2LfoXTWDUVPTC4V3MUEKZm48W+XYpeWSZCv+vYF1ZABUm2CqnDVf1sFtIYrj7KQ==";
      };
    };
    "@octokit/graphql-4.6.1" = {
      name = "_at_octokit_slash_graphql";
      packageName = "@octokit/graphql";
      version = "4.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/graphql/-/graphql-4.6.1.tgz";
        sha512 = "2lYlvf4YTDgZCTXTW4+OX+9WTLFtEUc6hGm4qM1nlZjzxj+arizM4aHWzBVBCxY9glh7GIs0WEuiSgbVzv8cmA==";
      };
    };
    "@octokit/openapi-types-6.0.0" = {
      name = "_at_octokit_slash_openapi-types";
      packageName = "@octokit/openapi-types";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-6.0.0.tgz";
        sha512 = "CnDdK7ivHkBtJYzWzZm7gEkanA7gKH6a09Eguz7flHw//GacPJLmkHA3f3N++MJmlxD1Fl+mB7B32EEpSCwztQ==";
      };
    };
    "@octokit/plugin-paginate-rest-2.13.3" = {
      name = "_at_octokit_slash_plugin-paginate-rest";
      packageName = "@octokit/plugin-paginate-rest";
      version = "2.13.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-2.13.3.tgz";
        sha512 = "46lptzM9lTeSmIBt/sVP/FLSTPGx6DCzAdSX3PfeJ3mTf4h9sGC26WpaQzMEq/Z44cOcmx8VsOhO+uEgE3cjYg==";
      };
    };
    "@octokit/plugin-rest-endpoint-methods-4.15.0" = {
      name = "_at_octokit_slash_plugin-rest-endpoint-methods";
      packageName = "@octokit/plugin-rest-endpoint-methods";
      version = "4.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-rest-endpoint-methods/-/plugin-rest-endpoint-methods-4.15.0.tgz";
        sha512 = "1AF9GM/Ywk8ukUM5seDRj286GdFpdfsHeOrOPBV2rVtRN7MQNzRIcw8W5sb4JPerjQ0WcRRwAwQyufg64BxJkA==";
      };
    };
    "@octokit/request-5.4.15" = {
      name = "_at_octokit_slash_request";
      packageName = "@octokit/request";
      version = "5.4.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request/-/request-5.4.15.tgz";
        sha512 = "6UnZfZzLwNhdLRreOtTkT9n57ZwulCve8q3IT/Z477vThu6snfdkBuhxnChpOKNGxcQ71ow561Qoa6uqLdPtag==";
      };
    };
    "@octokit/request-error-2.0.5" = {
      name = "_at_octokit_slash_request-error";
      packageName = "@octokit/request-error";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request-error/-/request-error-2.0.5.tgz";
        sha512 = "T/2wcCFyM7SkXzNoyVNWjyVlUwBvW3igM3Btr/eKYiPmucXTtkxt2RBsf6gn3LTzaLSLTQtNmvg+dGsOxQrjZg==";
      };
    };
    "@octokit/types-6.13.0" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "6.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-6.13.0.tgz";
        sha512 = "W2J9qlVIU11jMwKHUp5/rbVUeErqelCsO5vW5PKNb7wAXQVUz87Rc+imjlEvpvbH8yUb+KHmv8NEjVZdsdpyxA==";
      };
    };
    "@types/node-14.14.37" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "14.14.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-14.14.37.tgz";
        sha512 = "XYmBiy+ohOR4Lh5jE379fV2IU+6Jn4g5qASinhitfyO71b/sCo6MKsMLF5tc7Zf2CE8hViVQyYSobJNke8OvUw==";
      };
    };
    "@vercel/ncc-0.28.2" = {
      name = "_at_vercel_slash_ncc";
      packageName = "@vercel/ncc";
      version = "0.28.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vercel/ncc/-/ncc-0.28.2.tgz";
        sha512 = "2ZBPviK9nFHzymu9POKGz50BRGGBIw7a8VcjgH73Xu2H4IvZx3KS0Qk/SS7S/N6iAalAGGxLSwFM1obeBGWXGg==";
      };
    };
    "before-after-hook-2.2.1" = {
      name = "before-after-hook";
      packageName = "before-after-hook";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/before-after-hook/-/before-after-hook-2.2.1.tgz";
        sha512 = "/6FKxSTWoJdbsLDF8tdIjaRiFXiE6UHsEHE3OPI/cwPURCVi1ukP0gmLn7XWEiFk5TcwQjjY5PWsU+j+tgXgmw==";
      };
    };
    "deprecation-2.3.1" = {
      name = "deprecation";
      packageName = "deprecation";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deprecation/-/deprecation-2.3.1.tgz";
        sha512 = "xmHIy4F3scKVwMsQ4WnVaS8bHOx0DmVwRywosKhaILI0ywMDWPtBSku2HNxRvF7jtwDRsoEwYQSfbxj8b7RlJQ==";
      };
    };
    "is-plain-object-5.0.0" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-5.0.0.tgz";
        sha512 = "VRSzKkbMm5jMDoKLbltAkFQ5Qr7VDiTFGXxYFXXowVj387GeGNOCsOH6Msy00SGZ3Fp84b1Naa1psqgcCIEP5Q==";
      };
    };
    "node-fetch-2.6.1" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.1.tgz";
        sha512 = "V4aYg89jEoVRxRb2fJdAg8FHvI7cEyYdVAh94HH0UIK8oJxUfkjlDQN9RbMx+bEjP7+ggMiFRprSti032Oipxw==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "prettier-2.2.1" = {
      name = "prettier";
      packageName = "prettier";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-2.2.1.tgz";
        sha512 = "PqyhM2yCjg/oKkFPtTGUojv7gnZAoG80ttl45O6x2Ug/rMJw4wcc9k6aaf2hibP7BGVCCM33gZoGjyvt9mm16Q==";
      };
    };
    "tunnel-0.0.6" = {
      name = "tunnel";
      packageName = "tunnel";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel/-/tunnel-0.0.6.tgz";
        sha512 = "1h/Lnq9yajKY2PEbBadPXj3VxsDDu844OnaAo52UVmIzIvwwtBPIuNvkjuzBlTWpfJyUbG3ez0KSBibQkj4ojg==";
      };
    };
    "typescript-4.2.4" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.2.4.tgz";
        sha512 = "V+evlYHZnQkaz8TRBuxTA92yZBPotr5H+WhQ7bD3hZUndx5tGOa1fuCgeSjxAzM1RiN5IzvadIXTVefuuwZCRg==";
      };
    };
    "universal-user-agent-6.0.0" = {
      name = "universal-user-agent";
      packageName = "universal-user-agent";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/universal-user-agent/-/universal-user-agent-6.0.0.tgz";
        sha512 = "isyNax3wXoKaulPDZWHQqbmIx1k2tb9fb3GGDBRxCscfYV2Ch7WxPArBsFEG8s/safwXTT7H4QGhaIkTp9447w==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
  };
  args = {
    name = "nix-profile-action";
    packageName = "nix-profile-action";
    version = "1.0.0";
    src = ./..;
    dependencies = [
      sources."@actions/core-1.2.6"
      sources."@actions/exec-1.0.4"
      sources."@actions/github-4.0.0"
      sources."@actions/http-client-1.0.11"
      sources."@actions/io-1.1.0"
      sources."@octokit/auth-token-2.4.5"
      sources."@octokit/core-3.4.0"
      sources."@octokit/endpoint-6.0.11"
      sources."@octokit/graphql-4.6.1"
      sources."@octokit/openapi-types-6.0.0"
      sources."@octokit/plugin-paginate-rest-2.13.3"
      sources."@octokit/plugin-rest-endpoint-methods-4.15.0"
      sources."@octokit/request-5.4.15"
      sources."@octokit/request-error-2.0.5"
      sources."@octokit/types-6.13.0"
      sources."@types/node-14.14.37"
      sources."@vercel/ncc-0.28.2"
      sources."before-after-hook-2.2.1"
      sources."deprecation-2.3.1"
      sources."is-plain-object-5.0.0"
      sources."node-fetch-2.6.1"
      sources."once-1.4.0"
      sources."prettier-2.2.1"
      sources."tunnel-0.0.6"
      sources."typescript-4.2.4"
      sources."universal-user-agent-6.0.0"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A GitHub Action to install an ephemeral Nix profile";
      license = "Apache-2.0";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ]
        args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
