name: 'Install Nix Packages'
description: 'Install flake packages using an ephemeral Nix profile'
branding:
  icon: 'loader'
  color: 'gray-dark'
inputs:
  packages:
    description: 'Comma-separated list of flake package references to install'
    required: false
  expr:
    description: 'Install a derivation by evaluating the given expression'
    required: false
  inputs-from:
    description: 'Use inputs of the given flake as registry entries'
    default: "."
    required: false
outputs:
  nix_profile_path:
    description: 'Path to the Nix profile the requested packages were installed to'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  post-if: env.STATE_NIX_PROFILE_TMPDIR != ''

