name: 'Install Nix Profile'
description: 'A GitHub Action to install an ephemeral Nix profile'
inputs:
  packages:
    description: 'The packages you want to install'
    required: false
  expr:
    description: 'Install the given Nix expression into the profile.'
    required: false
  inputs-from:
    description: 'Use inputs of the given flake as registry entries'
    default: "."
    required: false
outputs:
  nix_profile_path:
    description: 'Path to the Nix profile the requested packages were installed to'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  post-if: env.STATE_NIX_PROFILE_TMPDIR != ''

