name: 'CI'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  check:
    name: Run our Action
    runs-on: ubuntu-latest
    env:
      GC_DONT_GC: 1
    strategy:
      matrix:
        fetch-depth:
          - 0 # all history
          - 1 # shallow clone
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ matrix.fetch-depth }}

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes ca-references recursive-nix

      - name: Run Action (packages)
        uses: ./
        with:
          packages: 'hello'

      - name: Run hello
        run: |
          hello

      - name: Run Action (expr)
        uses: ./
        with:
          expr: 'pkgs.figlet'

      - name: List installed packages
        run:
          nix profile list --profile "$STATE_NIX_PROFILE_TMPDIR"/.nix-profile

      - name: Run figlet
        run: |
          figlet WURZELPFROPF

  build:
    name: Build bundled action
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # We need a full checkout for a Git diff
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes ca-references recursive-nix

      - name: Install job dependencies
        uses: ./
        with:
          expr: 'pkgs.python3.withPackages (ps: [ps.GitPython])'

      - name: Build action
        run: |
          python .github/steps/build_action.py

  coverage:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # We need a full checkout for the tests
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes ca-references recursive-nix

      - name: Run tests with coverage
        run: |
          nix develop -c npm install
          nix develop -c npm run coverage

      - name: Install job dependencies
        if: github.ref == 'refs/heads/main'
        uses: ./
        with:
          expr: |
            pkgs.python3.withPackages (ps: with ps; [ ghp-import ])

      - name: Push badge
        if: github.ref == 'refs/heads/main'
        run: |
          python .github/steps/push_badge.py
